name: Test Cloudflare Worker Transport

permissions:
  contents: read
  pull-requests: read
  checks: write

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  test-cf:
    if: ${{ github.event.issue.pull_request && github.event.comment.user.type == 'Bot' && github.event.comment.user.html_url == 'https://github.com/apps/cloudflare-workers-and-pages' && contains(github.event.comment.body, 'Deployment successful') }}
    runs-on: ubuntu-latest

    steps:
      - name: Initialize check status
        id: start_check
        uses: actions/github-script@v9
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const pr = await github.rest.pulls.get({ owner, repo, pull_number: number });
            const { data } = await github.rest.checks.create({
              owner,
              repo,
              name: 'Cloudflare Worker Transport Test',
              head_sha: pr.data.head.sha,
              status: 'in_progress',
            });
            return data.id;
      - name: Get deployment URL
        id: get_url
        uses: actions/github-script@v9
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        with:
          result-encoding: string
          script: |
            const body = process.env.COMMENT_BODY;
            const urlMatches = body.matchAll(/https:\/\/[^\s]+\.workers\.dev/g)?.toArray()?.flat();
            if (!urlMatches) {
              core.setFailed('No deployment URL found.');
              return;
            }
            return urlMatches[0];

      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Prepare inspector
        run: npm install -g @modelcontextprotocol/inspector
      - name: Run and test Cloudflare Worker transport
        env:
          CF_WORKER_URL: ${{ steps.get_url.outputs.result }}
          CF_ACCESS_CLIENT_ID: ${{ secrets.CF_ACCESS_CLIENT_ID }}
          CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
        run: pwsh -File "./tests/run_test_cf.ps1"

      - name: Update check status
        if: ${{ always() && steps.start_check.conclusion == 'success' }}
        uses: actions/github-script@v9
        env:
          JOB_STATUS: ${{ job.status }}
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const checkId = ${{ steps.start_check.outputs.result }};
            await github.rest.checks.update({
              owner,
              repo,
              check_run_id: checkId,
              status: 'completed',
              conclusion: process.env.JOB_STATUS === 'success' ? 'success' : 'failure',
              output: {
                title: `Cloudflare Worker Transport Test`,
                summary: `Test ${process.env.JOB_STATUS}.\nDetails: https://github.com/${owner}/${repo}/actions/runs/${context.runId}`,
              },
            });
